GET http://localhost:8001/member/test/get
Accept: application/json

###
GET http://localhost:8000/member/member/count


###
POST http://localhost:8000/member/member/register
Content-Type: application/json

{
  "mobile": "18093885990"
}

###
POST http://localhost:8000/member/member/send-code
Content-Type: application/json

{
  "mobile": "18093885990"
}

###
POST http://localhost:8000/member/member/login
Content-Type: application/json

{
  "mobile": "18093885990",
  "code": "8888"
}

> {%
client.log(JSON.stringify(response.body));
client.global.set("token", response.body.content.token);
%}
