server:
  port: 8002
  servlet:
    context-path: /business

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train_business
    password: 775821
  devtools:
    livereload:
      # 防止热部署端口冲突
      port: 35732
  application:
    name: business
  data:
    redis:
      host: 192.168.29.130
      port: 6379
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: train_cache_
      # 允许Springboot缓存 null
      cache-null-values: true
      time-to-live: 60s

# mybatis xml 路径
mybatis:
  configuration:
    # 每执行一个sql，就清空本地缓存，相当于关闭了一级缓存（要打开事务 ->> @Transactional）
    local-cache-scope: statement
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com:
      ming:
        train:
          business:
            mapper: trace

rocketmq:
  name-server: http://localhost:9876
  producer:
    group: default
