server:
  port: 8003
  servlet:
    context-path: /batch

spring:
  application:
    name: batch
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/train_batch?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train_batch
    password: 775821
  devtools:
    livereload:
      # 防止热部署端口冲突
      port: 35733
# mybatis xml 路径
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com:
      ming:
        train:
          batch:
            mapper: trace
